// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DomainLayer.Common;
using System;
using System.Collections.Generic;

namespace DomainLayer.Models;

public partial class Stock:BaseDomain
{

    public int Id { get; set; }

    public string Symbol { get; set; }

    public string Code { get; set; }

    public decimal CurrentPrice { get; set; }

    public DateTime TimeStamps { get; set; }

    public virtual ICollection<StockHistory> StockHistories { get; set; } = new List<StockHistory>();
}