// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DomainLayer.Common;
using System;
using System.Collections.Generic;

namespace DomainLayer.Models;

public partial class StockHistory:BaseDomain
{

    public int Id { get; set; }

    public string Symbol { get; set; }

    public decimal CurrentPrice { get; set; }

    public DateTime TimeStamps { get; set; }

    public int FkStockId { get; set; }

    public virtual Stock FkStock { get; set; }
}