// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DomainLayer.Common;
using System;
using System.Collections.Generic;

namespace DomainLayer.Models;

public partial class User:BaseDomain
{

    public int Id { get; set; }

    public string Name { get; set; }

    public string UserName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }
}